//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.JobsPage.resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.Dashboard.JobsPage.resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string Common_Day {
            get {
                return ResourceManager.GetString("Common_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hour 的本地化字符串。
        /// </summary>
        internal static string Common_Hour {
            get {
                return ResourceManager.GetString("Common_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string Common_Minute {
            get {
                return ResourceManager.GetString("Common_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string Common_Month {
            get {
                return ResourceManager.GetString("Common_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second 的本地化字符串。
        /// </summary>
        internal static string Common_Second {
            get {
                return ResourceManager.GetString("Common_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        internal static string Common_Week {
            get {
                return ResourceManager.GetString("Common_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string Common_Year {
            get {
                return ResourceManager.GetString("Common_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Analysis {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and runs once every 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_AndRunsOnceEvery {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_AndRunsOnceEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assigned 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_Assigned {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every minute (Permitted wildcard character[, - * /]) 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_EveryMinute {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minutes 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_Minutes {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start to begin at 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_StartToBeginAt {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_StartToBeginAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time range is from 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Minute_TimeRangeIsFrom {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Minute_TimeRangeIsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_Tabpanel_Result {
            get {
                return ResourceManager.GetString("CronJobsPage_Tabpanel_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common Cron Expressions 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_TabTitle_CommonCronExpressions {
            get {
                return ResourceManager.GetString("CronJobsPage_TabTitle_CommonCronExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron Expression Analysis 的本地化字符串。
        /// </summary>
        internal static string CronJobsPage_TabTitle_CronExpressionAnalysis {
            get {
                return ResourceManager.GetString("CronJobsPage_TabTitle_CronExpressionAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This job does not require inputs 的本地化字符串。
        /// </summary>
        internal static string JobDoseNotRequireInputs {
            get {
                return ResourceManager.GetString("JobDoseNotRequireInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delayed 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_Delayed {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_Delayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delayed Execution 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_DelayedExecution {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_DelayedExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a time 00:00:00 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_DelayedExecution_Placeholder {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_DelayedExecution_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Immediate 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_Immediate {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue Execution 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_ImmediateExecution {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_ImmediateExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeating 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_Repeating {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_Repeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeated Execution 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_RepeatingExecution {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_RepeatingExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron Expression Builder 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_RepeatingExecution_Builder {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_RepeatingExecution_Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  * * * * * 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_RepeatingExecution_Placeholder {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_RepeatingExecution_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a cron expression or use the builder by clicking on the wrench 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_RepeatingExecution_TitleTip {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_RepeatingExecution_TitleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_Scheduled {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled  Execution 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_ScheduleExecution {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_ScheduleExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a Date 的本地化字符串。
        /// </summary>
        internal static string JobManagementPage_TaskType_ScheduleExecution_Placeholder {
            get {
                return ResourceManager.GetString("JobManagementPage_TaskType_ScheduleExecution_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task type 的本地化字符串。
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} was not in a correct format. 的本地化字符串。
        /// </summary>
        internal static string VerifyInfo_FormatNotCorrect {
            get {
                return ResourceManager.GetString("VerifyInfo_FormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is required. 的本地化字符串。
        /// </summary>
        internal static string VerifyInfo_Required {
            get {
                return ResourceManager.GetString("VerifyInfo_Required", resourceCulture);
            }
        }
    }
}
