#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.JobsPage.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\ManannaPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManannaPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n<link rel=\"stylesheet\" type=\"text /css\" href=\"");


            
            #line 5 "..\..\Pages\ManannaPage.cshtml"
                                         Write(Url.To($"{UrlRoute}/jsmcss"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n \r\n    <div class=\"row\">\r\n        <div class=\"col-md-3\">\r\n        ");


            
            #line 9 "..\..\Pages\ManannaPage.cshtml"
   Write(Html.RenderPartial(new CustomSidebarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
        <div class=""col-md-9"">
            <h1 class=""page-header mgmt-title"">sdfsdf</h1>
            <div class=""visible-md-block visible-lg-block"">
               <p class=""d-none""> Select a page from the menu on the left to see the jobs available.</p>
				<p class=""d-block""> 在左侧选择需要管理的任务</p>
            </div>
            <div class=""hidden-md hidden-lg"">
               <p class=""d-none"">  Select a page from the tabs at the top to see the jobs available.</p>
					<p class=""d-block""> 再上方选择需要管理的任务</p>
            </div>
        </div>
    </div>");


        }
    }
}
#pragma warning restore 1591
