#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.JobsPage.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.JobsPage.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.JobsPage.resx;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("\r\n");


            
            #line 7 "..\..\Pages\ManagementPage.cshtml"
  
    Layout = new LayoutPage(Title);  // 设置布局页


            
            #line default
            #line hidden
WriteLiteral("<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 10 "..\..\Pages\ManagementPage.cshtml"
                                        Write(Url.To(@UrlRoute+"/jsmcss"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n\r\n<div class=\"container\">\r\n    <div class=\"row\">\r\n        <div class=\"col" +
"-md-3\">\r\n\r\n            ");


            
            #line 17 "..\..\Pages\ManagementPage.cshtml"
       Write(Html.RenderPartial(new SideBarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"col-md-9\">\r\n            <h1 class=\"page-h" +
"eader mgmt-title\">");


            
            #line 21 "..\..\Pages\ManagementPage.cshtml"
                                          Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            <div class=\"visible-md-block visible-lg-block\">\r\n             " +
"   <p class=\"d-block\">");


            
            #line 23 "..\..\Pages\ManagementPage.cshtml"
                              Write(Resource.PageDescriptionLeft);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n            <div class=\"hidden-md hidden-lg\">\r\n        " +
"        <p class=\"d-block\">");


            
            #line 26 "..\..\Pages\ManagementPage.cshtml"
                              Write(Resource.PageDescriptionTop);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n            <div class=\"container mt-5\">\r\n             " +
"   <h1 class=\"text-center text-primary mb-5\">任务管理操作手册</h1>\r\n\r\n                <d" +
"iv class=\"row\">\r\n                    <div class=\"col-md-12\">\r\n                  " +
"      <h2 class=\"h4 font-weight-bold text-dark mb-3\">1. 任务管理概述</h2>\r\n           " +
"             <p class=\"lead text-muted\">\r\n                            本系统提供了强大的任" +
"务管理功能，支持任务的即时执行、定时执行、延时执行和循环执行。系统采用 Hangfire 进行后台任务处理，并集成了 Hangfire Dashboard 让用" +
"户可以方便地查看和管理任务。\r\n                        </p>\r\n                        <p class=\"" +
"text-muted\">\r\n                            用户可以通过任务管理页面对任务进行如下操作：\r\n              " +
"          </p>\r\n                        <ul class=\"list-group list-group-flush\">" +
"\r\n                            <li class=\"list-group-item\">立即执行任务</li>\r\n         " +
"                   <li class=\"list-group-item\">定时执行任务</li>\r\n                    " +
"        <li class=\"list-group-item\">延时执行任务</li>\r\n                            <li" +
" class=\"list-group-item\">循环执行任务</li>\r\n                        </ul>\r\n           " +
"         </div>\r\n                </div>\r\n\r\n                <div class=\"row mt-4\"" +
">\r\n                    <div class=\"col-md-12\">\r\n                        <h2 clas" +
"s=\"h4 font-weight-bold text-dark mb-4\">2. 操作步骤</h2>\r\n\r\n                        <" +
"div class=\"card mb-4\">\r\n                            <div class=\"card-body\">\r\n   " +
"                             <h3 class=\"h5 font-weight-bold text-primary\">2.1 立即" +
"执行任务</h3>\r\n                                <p>\r\n                                " +
"    立即执行任务是指立即启动某个后台任务。请按照以下步骤操作：\r\n                                </p>\r\n       " +
"                         <ul class=\"list-group\">\r\n                              " +
"      <li class=\"list-group-item\">在任务管理页面中，点击“立即执行”按钮。</li>\r\n                   " +
"                 <li class=\"list-group-item\">任务将立即执行，您可以在后台查看执行结果。</li>\r\n       " +
"                         </ul>\r\n                                <p class=\"mt-3 t" +
"ext-muted\"><strong>示例：</strong></p>\r\n                                <img src=\"~" +
"/images/execute-now-example.png\" alt=\"立即执行任务示例\" class=\"img-fluid rounded\" />\r\n  " +
"                          </div>\r\n                        </div>\r\n\r\n            " +
"            <div class=\"card mb-4\">\r\n                            <div class=\"car" +
"d-body\">\r\n                                <h3 class=\"h5 font-weight-bold text-pr" +
"imary\">2.2 定时执行任务</h3>\r\n                                <p>\r\n                   " +
"                 定时执行任务是指根据用户选择的时间，自动在指定时间执行任务。请按照以下步骤操作：\r\n                     " +
"           </p>\r\n                                <ul class=\"list-group\">\r\n      " +
"                              <li class=\"list-group-item\">在任务管理页面中，找到“定时执行任务”部分。" +
"</li>\r\n                                    <li class=\"list-group-item\">选择您希望任务执行" +
"的具体日期和时间。</li>\r\n                                    <li class=\"list-group-item\">" +
"点击“定时执行”按钮，任务将在指定时间自动执行。</li>\r\n                                </ul>\r\n          " +
"                      <p class=\"mt-3 text-muted\"><strong>示例：</strong></p>\r\n     " +
"                           <img src=\"~/images/schedule-job-example.png\" alt=\"定时执" +
"行任务示例\" class=\"img-fluid rounded\" />\r\n                            </div>\r\n       " +
"                 </div>\r\n\r\n                        <div class=\"card mb-4\">\r\n    " +
"                        <div class=\"card-body\">\r\n                               " +
" <h3 class=\"h5 font-weight-bold text-primary\">2.3 延时执行任务</h3>\r\n                 " +
"               <p>\r\n                                    延时执行任务是指在指定的延迟时间后执行任务。例如" +
"，您可以设置任务在 10 秒后执行。请按照以下步骤操作：\r\n                                </p>\r\n            " +
"                    <ul class=\"list-group\">\r\n                                   " +
" <li class=\"list-group-item\">在任务管理页面中，找到“延时执行任务”部分。</li>\r\n                      " +
"              <li class=\"list-group-item\">输入延迟时间（单位为秒）。</li>\r\n                  " +
"                  <li class=\"list-group-item\">点击“延时执行”按钮，任务将在指定的延迟时间后执行。</li>\r\n " +
"                               </ul>\r\n                                <p class=\"" +
"mt-3 text-muted\"><strong>示例：</strong></p>\r\n                                <img " +
"src=\"~/images/delayed-job-example.png\" alt=\"延时执行任务示例\" class=\"img-fluid rounded\" " +
"/>\r\n                            </div>\r\n                        </div>\r\n\r\n      " +
"                  <div class=\"card mb-4\">\r\n                            <div clas" +
"s=\"card-body\">\r\n                                <h3 class=\"h5 font-weight-bold t" +
"ext-primary\">2.4 循环执行任务</h3>\r\n                                <p>\r\n             " +
"                       循环执行任务是指定期执行某个任务（例如每分钟或每天执行一次）。请按照以下步骤操作：\r\n              " +
"                  </p>\r\n                                <ul class=\"list-group\">\r" +
"\n                                    <li class=\"list-group-item\">在任务管理页面中，找到“循环执" +
"行任务”部分。</li>\r\n                                    <li class=\"list-group-item\">输入" +
"一个有效的 Cron 表达式，用于定义任务的执行频率。</li>\r\n                                    <li class=" +
"\"list-group-item\">点击“设置循环执行”按钮，任务将按指定频率循环执行。</li>\r\n                             " +
"   </ul>\r\n                                <p class=\"mt-3 text-muted\"><strong>示例：" +
"</strong></p>\r\n                                <img src=\"~/images/recurring-job-" +
"example.png\" alt=\"循环执行任务示例\" class=\"img-fluid rounded\" />\r\n                      " +
"      </div>\r\n                        </div>\r\n                    </div>\r\n      " +
"          </div>\r\n\r\n                <div class=\"row mt-4\">\r\n                    " +
"<div class=\"col-md-12\">\r\n                        <h2 class=\"h4 font-weight-bold " +
"text-dark mb-4\">3. 常见问题 (FAQ)</h2>\r\n\r\n                        <div class=\"card m" +
"b-4\">\r\n                            <div class=\"card-body\">\r\n                    " +
"            <h5 class=\"h6 font-weight-bold text-dark\">Q1: 如何查看当前任务的执行状态？</h5>\r\n " +
"                               <p>您可以通过 Hangfire Dashboard 查看任务的执行状态、执行日志以及任务的运行" +
"历史。只需访问系统的 <strong>/hangfire</strong> 页面。</p>\r\n                            </div" +
">\r\n                        </div>\r\n\r\n                        <div class=\"card mb" +
"-4\">\r\n                            <div class=\"card-body\">\r\n                     " +
"           <h5 class=\"h6 font-weight-bold text-dark\">Q2: 如果任务执行失败，如何处理？</h5>\r\n  " +
"                              <p>当任务执行失败时，Hangfire 会自动进行重试。您可以在 Hangfire Dashboa" +
"rd 中查看失败的任务，并重新启动它们。</p>\r\n                            </div>\r\n                  " +
"      </div>\r\n\r\n                        <div class=\"card mb-4\">\r\n               " +
"             <div class=\"card-body\">\r\n                                <h5 class=" +
"\"h6 font-weight-bold text-dark\">Q3: 如何修改任务的执行计划？</h5>\r\n                         " +
"       <p>如果需要修改任务的执行计划，可以在管理页面中删除当前任务并重新安排新的执行计划。</p>\r\n                        " +
"    </div>\r\n                        </div>\r\n\r\n                        <div class" +
"=\"card mb-4\">\r\n                            <div class=\"card-body\">\r\n            " +
"                    <h5 class=\"h6 font-weight-bold text-dark\">Q4: 为什么定时任务有时会延迟执行" +
"？</h5>\r\n                                <p>定时任务可能会受到服务器资源、网络状况或其他因素的影响。如果遇到延迟，建议" +
"检查服务器的负载情况或日志信息。</p>\r\n                            </div>\r\n                      " +
"  </div>\r\n\r\n                        <div class=\"card mb-4\">\r\n                   " +
"         <div class=\"card-body\">\r\n                                <h5 class=\"h6 " +
"font-weight-bold text-dark\">Q5: 如何删除一个任务？</h5>\r\n                                " +
"<p>您可以在 Hangfire Dashboard 中找到该任务并手动删除，或者通过编程方式取消任务的执行。</p>\r\n                   " +
"         </div>\r\n                        </div>\r\n                    </div>\r\n   " +
"             </div>\r\n\r\n                <div class=\"row mt-4\">\r\n                 " +
"   <div class=\"col-md-12\">\r\n                        <h2 class=\"h4 font-weight-bo" +
"ld text-dark mb-4\">4. 联系我们</h2>\r\n                        <p>如果您在使用过程中遇到问题或有其他疑问，" +
"请通过以下方式联系我们：</p>\r\n                        <ul class=\"list-group\">\r\n             " +
"               <li class=\"list-group-item\">邮箱: <a href=\"mailto:support@example.c" +
"om\">support@example.com</a></li>\r\n                            <li class=\"list-gr" +
"oup-item\">电话: <a href=\"tel:+1234567890\">123-456-7890</a></li>\r\n                 " +
"           <li class=\"list-group-item\">技术支持: <a href=\"http://support.example.com" +
"\" target=\"_blank\">http://support.example.com</a></li>\r\n                        <" +
"/ul>\r\n\r\n\r\n                    </div>\r\n\r\n\r\n\r\n                </div>\r\n\r\n          " +
"  </div>\r\n        </div>\r\n\r\n\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
