#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.JobsPage.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\Shared\SideBarMenu.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\Shared\SideBarMenu.cshtml"
    using Hangfire.Dashboard.JobsPage;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Shared\SideBarMenu.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SideBarMenu : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");





WriteLiteral("\r\n\r\n<ul class=\"nav nav-tabs hidden-md hidden-lg\">\r\n");


            
            #line 10 "..\..\Pages\Shared\SideBarMenu.cshtml"
     foreach (var item in Items)
    {
        var itemValue = item(this);
        var activeClass = itemValue.Active ? "active" : "";

            
            #line default
            #line hidden
WriteLiteral("        <li role=\"presentation\" class=\"");


            
            #line 14 "..\..\Pages\Shared\SideBarMenu.cshtml"
                                  Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <a href=\"");


            
            #line 15 "..\..\Pages\Shared\SideBarMenu.cshtml"
                Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 16 "..\..\Pages\Shared\SideBarMenu.cshtml"
           Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span class=\"pull-right\">\r\n                </span>\r\n           " +
" </a>\r\n        </li>\r\n");


            
            #line 21 "..\..\Pages\Shared\SideBarMenu.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</ul>\r\n\r\n<ul class=\"nav nav-pills nav-stacked visible-md-block visible-lg-block" +
"\">\r\n\r\n");


            
            #line 27 "..\..\Pages\Shared\SideBarMenu.cshtml"
     foreach (var item in Items)
    {
        var itemValue = item(this);
        var activeClass = itemValue.Active ? "active" : "";

            
            #line default
            #line hidden
WriteLiteral("        <li role=\"presentation\" class=\"");


            
            #line 31 "..\..\Pages\Shared\SideBarMenu.cshtml"
                                  Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <a href=\"");


            
            #line 32 "..\..\Pages\Shared\SideBarMenu.cshtml"
                Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                ");


            
            #line 33 "..\..\Pages\Shared\SideBarMenu.cshtml"
           Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span class=\"pull-right\">\r\n                </span>\r\n           " +
" </a>\r\n        </li>\r\n");


            
            #line 38 "..\..\Pages\Shared\SideBarMenu.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</ul>");


        }
    }
}
#pragma warning restore 1591
