#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsPages4Hangfire.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\ManagementPage.cshtml"
    using JobsPages4Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementPage.cshtml"
    using JobsPages4Hangfire.Dashboard.resx;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementPage.cshtml"
    using JobsPages4Hangfire.Dashboard.Support;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\n");


            
            #line 8 "..\..\Pages\ManagementPage.cshtml"
  
    Layout = new LayoutPage(Title);  // 设置布局页
    Func<string, string> T = ManagementLocalization.Get;


            
            #line default
            #line hidden
WriteLiteral("<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 12 "..\..\Pages\ManagementPage.cshtml"
                                        Write(Url.To(@UrlRoute+"/jsmcss"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n\r\n\r\n<div class=\"container\">\r\n    <div class=\"row\">\r\n        <div class=\"col" +
"-md-3\">\r\n\r\n            ");


            
            #line 19 "..\..\Pages\ManagementPage.cshtml"
       Write(Html.RenderPartial(new SideBarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"col-md-9\">\r\n            <h1 class=\"page-h" +
"eader mgmt-title\">");


            
            #line 23 "..\..\Pages\ManagementPage.cshtml"
                                          Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n            <div class=\"visible-md-block visible-lg-block\">\r\n             " +
"   <p class=\"d-block\">");


            
            #line 25 "..\..\Pages\ManagementPage.cshtml"
                              Write(Resource.PageDescriptionLeft);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n            <div class=\"hidden-md hidden-lg\">\r\n        " +
"        <p class=\"d-block\">");


            
            #line 28 "..\..\Pages\ManagementPage.cshtml"
                              Write(Resource.PageDescriptionTop);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\n            <div class=\"management-manual mt-5\">\n       " +
"         <h1 class=\"text-center text-primary mb-5\">");


            
            #line 31 "..\..\Pages\ManagementPage.cshtml"
                                                     Write(T("Manual_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h1>\n\n                <div class=\"row\">\n                    <div class=\"col-md-1" +
"2\">\n                        <h2 class=\"h4 font-weight-bold text-dark mb-3\">1. ");


            
            #line 35 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Overview_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\n                        <p class=\"lead text-muted\">\n                       " +
"     ");


            
            #line 37 "..\..\Pages\ManagementPage.cshtml"
                       Write(T("Manual_Overview_Lead"));

            
            #line default
            #line hidden
WriteLiteral("\n                        </p>\n                        <p class=\"text-muted\">\n    " +
"                        ");


            
            #line 40 "..\..\Pages\ManagementPage.cshtml"
                       Write(T("Manual_Overview_Intro"));

            
            #line default
            #line hidden
WriteLiteral("\n                        </p>\n                        <ul class=\"list-group list-" +
"group-flush\">\n                            <li class=\"list-group-item\">");


            
            #line 43 "..\..\Pages\ManagementPage.cshtml"
                                                   Write(T("Manual_Action_Immediate"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                            <li class=\"list-group-item\">");


            
            #line 44 "..\..\Pages\ManagementPage.cshtml"
                                                   Write(T("Manual_Action_Scheduled"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                            <li class=\"list-group-item\">");


            
            #line 45 "..\..\Pages\ManagementPage.cshtml"
                                                   Write(T("Manual_Action_Delayed"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                            <li class=\"list-group-item\">");


            
            #line 46 "..\..\Pages\ManagementPage.cshtml"
                                                   Write(T("Manual_Action_Recurring"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                        </ul>\n                    </div>\n                </" +
"div>\n\n                <div class=\"row mt-4\">\n                    <div class=\"col" +
"-md-12\">\n                        <h2 class=\"h4 font-weight-bold text-dark mb-4\">" +
"2. ");


            
            #line 53 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Steps_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n                        <div class=\"card mb-4\">\n                          " +
"  <div class=\"card-body\">\n                                <h3 class=\"h5 font-wei" +
"ght-bold text-primary\">2.1 ");


            
            #line 57 "..\..\Pages\ManagementPage.cshtml"
                                                                            Write(T("Manual_Immediate_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\n                                <p>\n                                    ");


            
            #line 59 "..\..\Pages\ManagementPage.cshtml"
                               Write(T("Manual_Immediate_Description"));

            
            #line default
            #line hidden
WriteLiteral("\n                                </p>\n                                <ul class=\"" +
"list-group\">\n                                    <li class=\"list-group-item\">");


            
            #line 62 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Immediate_Step1"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 63 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Immediate_Step2"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                </ul>\n                                <p cl" +
"ass=\"mt-3 text-muted\"><strong>");


            
            #line 65 "..\..\Pages\ManagementPage.cshtml"
                                                              Write(T("Manual_Example_Label"));

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\n                                <figure class=\"management-manual-im" +
"age\">\n                                    <img src=\"");


            
            #line 67 "..\..\Pages\ManagementPage.cshtml"
                                         Write(Url.To($"{UrlRoute}/images/execute-now-example.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 67 "..\..\Pages\ManagementPage.cshtml"
                                                                                                     Write(T("Manual_Immediate_ImageAlt"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                </figure>
                            </div>
                        </div>

                        <div class=""card mb-4"">
                            <div class=""card-body"">
                                <h3 class=""h5 font-weight-bold text-primary"">2.2 ");


            
            #line 74 "..\..\Pages\ManagementPage.cshtml"
                                                                            Write(T("Manual_Scheduled_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\n                                <p>\n                                    ");


            
            #line 76 "..\..\Pages\ManagementPage.cshtml"
                               Write(T("Manual_Scheduled_Description"));

            
            #line default
            #line hidden
WriteLiteral("\n                                </p>\n                                <ul class=\"" +
"list-group\">\n                                    <li class=\"list-group-item\">");


            
            #line 79 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Scheduled_Step1"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 80 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Scheduled_Step2"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 81 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Scheduled_Step3"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                </ul>\n                                <p cl" +
"ass=\"mt-3 text-muted\"><strong>");


            
            #line 83 "..\..\Pages\ManagementPage.cshtml"
                                                              Write(T("Manual_Example_Label"));

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\n                                <figure class=\"management-manual-im" +
"age\">\n                                    <img src=\"");


            
            #line 85 "..\..\Pages\ManagementPage.cshtml"
                                         Write(Url.To($"{UrlRoute}/images/schedule-job-example.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 85 "..\..\Pages\ManagementPage.cshtml"
                                                                                                      Write(T("Manual_Scheduled_ImageAlt"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                </figure>
                            </div>
                        </div>

                        <div class=""card mb-4"">
                            <div class=""card-body"">
                                <h3 class=""h5 font-weight-bold text-primary"">2.3 ");


            
            #line 92 "..\..\Pages\ManagementPage.cshtml"
                                                                            Write(T("Manual_Delayed_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\n                                <p>\n                                    ");


            
            #line 94 "..\..\Pages\ManagementPage.cshtml"
                               Write(T("Manual_Delayed_Description"));

            
            #line default
            #line hidden
WriteLiteral("\n                                </p>\n                                <ul class=\"" +
"list-group\">\n                                    <li class=\"list-group-item\">");


            
            #line 97 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Delayed_Step1"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 98 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Delayed_Step2"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 99 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Delayed_Step3"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                </ul>\n                                <p cl" +
"ass=\"mt-3 text-muted\"><strong>");


            
            #line 101 "..\..\Pages\ManagementPage.cshtml"
                                                              Write(T("Manual_Example_Label"));

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\n                                <figure class=\"management-manual-im" +
"age\">\n                                    <img src=\"");


            
            #line 103 "..\..\Pages\ManagementPage.cshtml"
                                         Write(Url.To($"{UrlRoute}/images/delayed-job-example.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 103 "..\..\Pages\ManagementPage.cshtml"
                                                                                                     Write(T("Manual_Delayed_ImageAlt"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                </figure>
                            </div>
                        </div>

                        <div class=""card mb-4"">
                            <div class=""card-body"">
                                <h3 class=""h5 font-weight-bold text-primary"">2.4 ");


            
            #line 110 "..\..\Pages\ManagementPage.cshtml"
                                                                            Write(T("Manual_Recurring_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\n                                <p>\n                                    ");


            
            #line 112 "..\..\Pages\ManagementPage.cshtml"
                               Write(T("Manual_Recurring_Description"));

            
            #line default
            #line hidden
WriteLiteral("\n                                </p>\n                                <ul class=\"" +
"list-group\">\n                                    <li class=\"list-group-item\">");


            
            #line 115 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Recurring_Step1"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 116 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Recurring_Step2"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                    <li class=\"list-group-item\">");


            
            #line 117 "..\..\Pages\ManagementPage.cshtml"
                                                           Write(T("Manual_Recurring_Step3"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n                                </ul>\n                                <p cl" +
"ass=\"mt-3 text-muted\"><strong>");


            
            #line 119 "..\..\Pages\ManagementPage.cshtml"
                                                              Write(T("Manual_Example_Label"));

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\n                                <figure class=\"management-manual-im" +
"age\">\n                                    <img src=\"");


            
            #line 121 "..\..\Pages\ManagementPage.cshtml"
                                         Write(Url.To($"{UrlRoute}/images/recurring-job-example.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 121 "..\..\Pages\ManagementPage.cshtml"
                                                                                                       Write(T("Manual_Recurring_ImageAlt"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>

                <div class=""row mt-4"">
                    <div class=""col-md-12"">
                        <h2 class=""h4 font-weight-bold text-dark mb-4"">3. ");


            
            #line 130 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_Title"));

            
            #line default
            #line hidden
WriteLiteral("</h2>\n\n                        <div class=\"card mb-4\">\n                          " +
"  <div class=\"card-body\">\n                                <h5 class=\"h6 font-wei" +
"ght-bold text-dark\">");


            
            #line 134 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_Status_Q"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\n                                <p>");


            
            #line 135 "..\..\Pages\ManagementPage.cshtml"
                              Write(T("Manual_Faq_Status_A"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n                            </div>\n                        </div>\n\n         " +
"               <div class=\"card mb-4\">\n                            <div class=\"c" +
"ard-body\">\n                                <h5 class=\"h6 font-weight-bold text-d" +
"ark\">");


            
            #line 141 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_Failure_Q"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\n                                <p>");


            
            #line 142 "..\..\Pages\ManagementPage.cshtml"
                              Write(T("Manual_Faq_Failure_A"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n                            </div>\n                        </div>\n\n         " +
"               <div class=\"card mb-4\">\n                            <div class=\"c" +
"ard-body\">\n                                <h5 class=\"h6 font-weight-bold text-d" +
"ark\">");


            
            #line 148 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_UpdateSchedule_Q"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\n                                <p>");


            
            #line 149 "..\..\Pages\ManagementPage.cshtml"
                              Write(T("Manual_Faq_UpdateSchedule_A"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n                            </div>\n                        </div>\n\n         " +
"               <div class=\"card mb-4\">\n                            <div class=\"c" +
"ard-body\">\n                                <h5 class=\"h6 font-weight-bold text-d" +
"ark\">");


            
            #line 155 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_Delay_Q"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\n                                <p>");


            
            #line 156 "..\..\Pages\ManagementPage.cshtml"
                              Write(T("Manual_Faq_Delay_A"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n                            </div>\n                        </div>\n\n         " +
"               <div class=\"card mb-4\">\n                            <div class=\"c" +
"ard-body\">\n                                <h5 class=\"h6 font-weight-bold text-d" +
"ark\">");


            
            #line 162 "..\..\Pages\ManagementPage.cshtml"
                                                                     Write(T("Manual_Faq_Delete_Q"));

            
            #line default
            #line hidden
WriteLiteral("</h5>\n                                <p>");


            
            #line 163 "..\..\Pages\ManagementPage.cshtml"
                              Write(T("Manual_Faq_Delete_A"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n                            </div>\n                        </div>\n          " +
"          </div>\n                </div>\n\n            </div>\n        </div>\n\r\n\r\n " +
"   </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
