#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsPages4Hangfire.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\ManagementJobsPage.cshtml"
    using Hangfire;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\ManagementJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementJobsPage.cshtml"
    using JobsPages4Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementJobsPage.cshtml"
    using JobsPages4Hangfire.Dashboard.resx;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementJobsPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");






WriteLiteral("\n");


            
            #line 8 "..\..\Pages\ManagementJobsPage.cshtml"
  
    Layout = new LayoutPage(Model.MenuName);
    var timeSpanItems = new Dictionary<string, string>() {
        { string.Format(Resource.Seconds, 5), "0:0:5" },
        { string.Format(Resource.Seconds, 10), "0:0:10" },
        { string.Format(Resource.Seconds, 15), "0:0:15" },
        { string.Format(Resource.Seconds, 30), "0:0:30" },
        { string.Format(Resource.Seconds, 60), "0:1:0" }
    };
    var cronItems = new Dictionary<string, string>() {
        { Resource.EveryMinute, Cron.Minutely() },
        { Resource.Hourly, Cron.Hourly() },
        { Resource.Daily, Cron.Daily() },
        { Resource.Weekly, Cron.Weekly() },
        { Resource.Monthly, Cron.Monthly() },
        { Resource.Annually, Cron.Yearly() }
    };
    var loadingText = Resource.Queuing;


            
            #line default
            #line hidden
WriteLiteral("\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 30 "..\..\Pages\ManagementJobsPage.cshtml"
   Write(Html.RenderPartial(new SideBarMenu(ManagementSidebarMenu.Items)));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div id=\"jobsAccordion\" class=\"col-md-9 accordion job-panels\">\n");


            
            #line 33 "..\..\Pages\ManagementJobsPage.cshtml"
         foreach (var modelSection in Model.Sections)
        {
            if (modelSection.ShowWrapper)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"panel panel-info card wrapper-panel\" data-id=\"section" +
"_");


            
            #line 37 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                              Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\">\n                    <div id=\"section_heading_");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                         Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-heading card-header ");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                         Write(modelSection.Expanded ? "" : "collapsed");

            
            #line default
            #line hidden
WriteLiteral("\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#jobsAccordion\" data-target=\"" +
"#section_collapse_");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                                       Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"#section_collapse_");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                                                                                              Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                                                                                                                                            Write(modelSection.Expanded ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral("\" aria-controls=\"section_collapse_");


            
            #line 38 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                         Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\">\n                        <h4 class=\"panel-title\">");


            
            #line 39 "..\..\Pages\ManagementJobsPage.cshtml"
                                           Write(modelSection.Title);

            
            #line default
            #line hidden
WriteLiteral("</h4>\n                    </div>\n                    <div id=\"section_collapse_");


            
            #line 41 "..\..\Pages\ManagementJobsPage.cshtml"
                                          Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 41 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                               Write(modelSection.Expanded ? "collapse in" : "collapse");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 41 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                     Write(modelSection.Expanded ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"section_heading_");


            
            #line 41 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                                   Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" data-parent=\"#jobsAccordion\">\n");


            
            #line 42 "..\..\Pages\ManagementJobsPage.cshtml"
                         foreach (var job in modelSection.Jobs)
                        {
                            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Pages\ManagementJobsPage.cshtml"
                       Write(RenderJobMarkup(job, timeSpanItems, cronItems, loadingText));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                        
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\n                </div>\n");


            
            #line 48 "..\..\Pages\ManagementJobsPage.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <h1 class=\"page-header single-section\">");


            
            #line 51 "..\..\Pages\ManagementJobsPage.cshtml"
                                                  Write(modelSection.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\n");



WriteLiteral("                <p class=\"lead\"> ");


            
            #line 52 "..\..\Pages\ManagementJobsPage.cshtml"
                            Write(Model.MenuDescription);

            
            #line default
            #line hidden
WriteLiteral(" </p>\n");



WriteLiteral("                <div id=\"section_collapse_");


            
            #line 53 "..\..\Pages\ManagementJobsPage.cshtml"
                                      Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 53 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                           Write(modelSection.Expanded ? "collapse in" : "collapse");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 53 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                 Write(modelSection.Expanded ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"section_heading_");


            
            #line 53 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                                                                                                                                                                               Write(modelSection.ScrubbedTitle);

            
            #line default
            #line hidden
WriteLiteral("\" data-parent=\"#jobsAccordion\">\n");


            
            #line 54 "..\..\Pages\ManagementJobsPage.cshtml"
                     foreach (var job in modelSection.Jobs)
                    {
                        
            
            #line default
            #line hidden
            
            #line 56 "..\..\Pages\ManagementJobsPage.cshtml"
                   Write(RenderJobMarkup(job, timeSpanItems, cronItems, loadingText));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                    
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\n");


            
            #line 59 "..\..\Pages\ManagementJobsPage.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral(@"    </div>
    <div class=""modal fade"" id=""cronModal"" tabindex=""-1"" role=""dialog"" aria-labelledby=""cronModalLabel"">
        <div class=""modal-dialog modal-lg"" role=""document"">
            <div class=""modal-content"">
                <div class=""modal-header"">
                    <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close""><span aria-hidden=""true"">&times;</span></button>
                    <h4 class=""modal-title"" id=""cronModalLabel"">");


            
            #line 67 "..\..\Pages\ManagementJobsPage.cshtml"
                                                           Write(Resource.JobManagementPage_TaskType_RepeatingExecution_Builder);

            
            #line default
            #line hidden
WriteLiteral("</h4>\n                </div>\n                <div class=\"modal-body\">\n           " +
"         ");


            
            #line 70 "..\..\Pages\ManagementJobsPage.cshtml"
               Write(Html.RenderPartial(new CronJobsPage()));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n                <div class=\"modal-footer\">\n              " +
"      <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">");


            
            #line 73 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                  Write(Resource.Close);

            
            #line default
            #line hidden
WriteLiteral("</button>\n                    <button type=\"button\" class=\"btn btn-primary\" id=\"c" +
"onnExpressionOk\">");


            
            #line 74 "..\..\Pages\ManagementJobsPage.cshtml"
                                                                                   Write(Resource.Ok);

            
            #line default
            #line hidden
WriteLiteral("</button>\n                </div>\n            </div>\n        </div>\n    </div>\n</d" +
"iv>\n<script>\n    function LoadJSM() {\n        var link2 = document.createElement" +
"(\'script\');\n        link2.setAttribute(\'src\', \'");


            
            #line 83 "..\..\Pages\ManagementJobsPage.cshtml"
                              Write(Url.To($"{ManagementPage.UrlRoute}/jsm"));

            
            #line default
            #line hidden
WriteLiteral(@"');
        document.getElementsByTagName('body')[0].appendChild(link2);
    }

    if (window.attachEvent) {
        window.attachEvent('onload', LoadJSM);
    }
    else {
        if (window.onload) {
            var curronload = window.onload;
            var newonload = function (evt) {
                curronload(evt);
                LoadJSM(evt);
            };
            window.onload = newonload;
        } else {
            window.onload = LoadJSM;
        }
    }
</script>
<link rel=""stylesheet"" type=""text/css"" href=""");


            
            #line 103 "..\..\Pages\ManagementJobsPage.cshtml"
                                        Write(Url.To($"{ManagementPage.UrlRoute}/jsmcss"));

            
            #line default
            #line hidden
WriteLiteral("\" />\n");


        }
    }
}
#pragma warning restore 1591
